"""initial schema

Revision ID: 69b8689f399d
Revises: 
Create Date: 2026-04-26 15:11:43.653293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69b8689f399d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('command', 'python', 'llm_judge', name='evaluatortype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('minimize', 'maximize', name='metricdirection'), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('baseline_required', sa.Boolean(), nullable=False),
    sa.Column('network_mode', sa.Enum('none', 'bridge', 'egress_proxy', name='networkmode'), nullable=False),
    sa.Column('network_allow', sa.JSON(), nullable=True),
    sa.Column('secret_refs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secrets_name'), ['name'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('target_file', sa.String(length=1024), nullable=False),
    sa.Column('program_md', sa.Text(), nullable=False),
    sa.Column('evaluator_id', sa.String(length=36), nullable=False),
    sa.Column('wall_clock_budget_s', sa.Integer(), nullable=False),
    sa.Column('token_cap_session', sa.Integer(), nullable=False),
    sa.Column('token_cap_iter', sa.Integer(), nullable=False),
    sa.Column('max_files_per_diff', sa.Integer(), nullable=False),
    sa.Column('review_mode', sa.Enum('always', 'improvements_only', 'auto_approve', name='reviewmode'), nullable=False),
    sa.Column('review_timeout_hours', sa.Integer(), nullable=False),
    sa.Column('worktree_prune_window', sa.Integer(), nullable=False),
    sa.Column('validation_retry_max', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'running', 'paused', 'draining', 'stopped', 'complete', name='sessionstatus'), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('session_branch', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('parent_commit', sa.String(length=64), nullable=True),
    sa.Column('experiment_commit', sa.String(length=64), nullable=True),
    sa.Column('branch_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'scored', 'awaiting_review', 'kept', 'reverted', 'failed', 'duplicate', name='experimentstatus'), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('diff_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_attempts', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'auto_rejected_timeout', 'auto_rejected_no_improvement', name='decision'), nullable=True),
    sa.Column('rejection_comment', sa.String(length=500), nullable=True),
    sa.Column('kept', sa.Boolean(), nullable=False),
    sa.Column('worktree_pruned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_experiments_session_diffhash', ['session_id', 'diff_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_experiments_session_iteration', ['session_id', 'iteration'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('stdout_path', sa.String(length=1024), nullable=True),
    sa.Column('stderr_path', sa.String(length=1024), nullable=True),
    sa.Column('metric_payload', sa.JSON(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_experiment_id'), ['experiment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_experiment_id'))

    op.drop_table('runs')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index('ix_experiments_session_iteration')
        batch_op.drop_index(batch_op.f('ix_experiments_session_id'))
        batch_op.drop_index('ix_experiments_session_diffhash')
        batch_op.drop_index(batch_op.f('ix_experiments_created_at'))

    op.drop_table('experiments')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_status'))

    op.drop_table('sessions')
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secrets_name'))

    op.drop_table('secrets')
    op.drop_table('evaluators')
    # ### end Alembic commands ###
